friendship/urls.py
from django.conf.urls.defaults import url, patterns
from friendship.views import view_friends, friendship_add_friend, friendship_accept, \
        friendship_reject, friendship_cancel, friendship_request_list, \
        friendship_request_list_rejected, friendship_requests_detail, followers,\
        following, follower_add, follower_remove, all_users

urlpatterns = patterns('',
    url(
        regex=r'^users/$',
        view=all_users,
        name='friendship_view_users',
    ),
    url(
        regex=r'^friends/(?P<username>[\w-]+)/$',
        view=view_friends,
        name='friendship_view_friends',
    ),
    url(
        regex=r'^friend/add/(?P<to_username>[\w-]+)/$',
        view=friendship_add_friend,
        name='friendship_add_friend',
    ),
    url(
        regex=r'^friend/accept/(?P<friendship_request_id>\d+)/$',
        view=friendship_accept,
        name='friendship_accept',
    ),
    url(
        regex=r'^friend/reject/(?P<friendship_request_id>\d+)/$',
        view=friendship_reject,
        name='friendship_reject',
    ),
    url(
        regex=r'^friend/cancel/(?P<friendship_request_id>\d+)/$',
        view=friendship_cancel,
        name='friendship_cancel',
    ),
    url(
        regex=r'^friend/requests/$',
        view=friendship_request_list,
        name='friendship_request_list',
    ),
    url(
        regex=r'^friend/requests/rejected/$',
        view=friendship_request_list_rejected,
        name='friendship_requests_rejected',
    ),
    url(
        regex=r'^friend/request/(?P<friendship_request_id>\d+)/$',
        view=friendship_requests_detail,
        name='friendship_requests_detail',
    ),
    url(
        regex=r'^followers/(?P<username>[\w-]+)/$',
        view=followers,
        name='friendship_followers',
    ),
    url(
        regex=r'^following/(?P<username>[\w-]+)/$',
        view=following,
        name='friendship_following',
    ),
    url(
        regex=r'^follower/add/(?P<followee_username>[\w-]+)/$',
        view=follower_add,
        name='follower_add',
    ),
    url(
        regex=r'^follower/remove/(?P<followee_username>[\w-]+)/$',
        view=follower_remove,
        name='follower_remove',
    ),
)

socialmenu/urls.py
from django.conf.urls import patterns, include, url
from menus.views import *
import os.path
from django.views.generic.simple import direct_to_template
from django.conf import settings
from django.contrib.auth.views import password_change

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

site_media = os.path.join(
  os.path.dirname(__file__), 'site_media'
)



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'socialmenu.views.home', name='home'),
    # url(r'^socialmenu/', include('socialmenu.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    (r'^$',main_page),
    (r'^popular/$',popular_page),
    (r'^all/$',all_page),
    (r'^user/(\w+)/$',user_page),
    (r'^user/(\w+)/(\w+)/$',user_subpage),
    (r'^menu/takeit/$',takeit),
    (r'^posttakeit/$',posttakeit),
    (r'^(\w+)/catagory/(\w+)/$',catagory_page),
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
    { 'document_root': site_media }),
    (r'^images/(?P<path>.*)$', 'django.views.static.serve',
    { 'document_root': settings.STATIC_ROOT }),
    (r'^register/$', register_page),
    (r'^submit_menu/$',menuSubmit_page),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^search/$', search_page),
    (r'^ajax/search/autocomplete/$', ajax_search_autocomplete),
    (r'^ajax_like',ajax_like),
    (r'^ajax_unlike',ajax_unlike),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^follow/(\w+)/$', follow),
    (r'^unfollow/(\w+)/$', unfollow),
    (r'^edit_profile/(\w+)/$',edit_profile),
    (r'^password/change/$',changepassword),
    (r'^prefs/$',emailsettings),
    (r'^delete/$',deactivate),
    (r'^zoomscroll/$',zoomscroll),
    (r'^ajax_edit_about/$',ajax_edit_about),
    (r'^about/$',about_page),
    (r'^about/(\w+)/$',about_subpage),
    (r'',include('social_auth.urls')),  
    (r'^reservation',reservation),
)

menus/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Catagory(models.Model):
    catagoryName = models.CharField(max_length=255)
    
class Restaurant(models.Model):
    ResName = models.CharField(max_length=255)
    ResLocation = models.CharField(max_length=255)
    ResPhone = models.CharField(max_length=20)
    ResType = models.ForeignKey(Catagory)
    
class Menu(models.Model):
    menuName = models.CharField(max_length=255)
    menuPrice = models.DecimalField(max_digits=5,decimal_places=2)
    menuCreateTime = models.DateTimeField(auto_now=True)
    menuStar = models.IntegerField()
    menuPics = models.ImageField(upload_to=settings.STATIC_ROOT)
    menuDescription = models.CharField(max_length=255)
    catagory = models.ForeignKey(Catagory)
    restaurant = models.ForeignKey(Restaurant)
    user = models.ForeignKey(User)
    
class LikedMenu(models.Model):
    menu = models.ForeignKey(Menu,unique=True)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=1)
    users_liked = models.ManyToManyField(User)
    def __str__(self):
        return '%s, %s' % self.menu, self.likes
    
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    firstname = models.CharField(max_length=25)
    lastname = models.CharField(max_length=25)
    gender = models.CharField(max_length=50,default="2")
    about = models.CharField(max_length=124,blank=True)
    location = models.CharField(max_length=100,blank=True)
    avatar = models.ImageField(upload_to=settings.STATIC_ROOT+"/avatar")
    loginwithfb = models.BooleanField(default=True)
    posttofbtimeline = models.BooleanField(default=True)
    loginwithtwitter = models.BooleanField(default=False)
    accoutStatus = models.BooleanField(default=False)
    emailOnComments = models.BooleanField(default=True)
    emailOnLikes = models.BooleanField(default=True)
    emailOnTakeIt = models.BooleanField(default=True)
    emailOnRecommend = models.BooleanField(default=True)
    emailOnFollows = models.BooleanField(default=True)
    emailFrequency = models.CharField(max_length=10,default="0")
    emailDigest = models.BooleanField(default=True)
    emailNewsUpdates = models.BooleanField(default=True)
    language = models.CharField(max_length=20,default="English")
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
post_save.connect(create_user_profile, sender=User)

from social_auth.signals import pre_update
from social_auth.backends.facebook import FacebookBackend
from social_auth.signals import socialauth_registered
import urllib
def facebook_extra_values(sender, user, response, details, **kwargs):
    profile,create = UserProfile.objects.get_or_create(user=user)
    profile.gender = response['gender']
    profile.firstname = response['first_name']
    profile.lastname = response['last_name']
    profile.loginwithfb = True
    profile.loginwithtwitter = False
    url = "http://graph.facebook.com/%s/picture?type=large" % response['id']
    avatar = urllib.urlopen(url).read()
    fout = open(settings.STATIC_ROOT+"/avatar/"+response['first_name']+'_'+response['last_name']+'_'+response['id'], "wb")
    fout.write(avatar)
    fout.close()
    profile.avatar = "avatar/"+response['first_name']+'_'+response['last_name']+'_'+response['id']
    profile.save()
    return True

pre_update.connect(facebook_extra_values, sender=FacebookBackend)

from social_auth.backends.twitter import TwitterBackend
def twitter_user_update(sender, user, response, details, **kwargs):
    profile, create = UserProfile.objects.get_or_create(user=user)
    try:
        first_name,last_name = response['name'].split(' ',1)
    except:
        first_name = response['name']
        last_name = ''
    profile.firstname = first_name
    profile.lastname = last_name
    profile.loginwithfb = False
    profile.loginwithtwitter = True
    url = response['profile_image_url']
    avatar = urllib.urlopen(url).read()
    fout = open(settings.STATIC_ROOT+"/avatar/"+first_name+"_"+last_name+"_"+response['id_str']+".jpg", "wb")
    fout.write(avatar)
    fout.close()
    profile.avatar = "avatar/"+first_name+"_"+last_name+"_"+response['id_str']+".jpg"
    profile.save()
    return True

pre_update.connect(twitter_user_update, sender=TwitterBackend)

socialmenu/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block head %}About{% endblock %}
{% block content %}
     {% include "main_header.html" %}
     <div id="AboutContainer">
        <div id="AboutContent">
            <div id="AboutLeft">
                <ul>
                    <li>
                        <a {% if not subpage %} class="selected loaded"{% endif %} href="/about/">
                            <span>What is Social Menu?</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                    <li>
                        <a {% if subpage == 'etiquette' %} class="selected loaded"{% endif %} href="/about/etiquette/">
                            <span>SocialMenu Etiquette</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                    <li>
                        <a {% if subpage == 'help' %} class="selected loaded"{% endif %} href="/about/help/">
                            <span>Getting Started</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                    <li>
                        <a {% if subpage == 'support' %} class="selected loaded"{% endif %} href="/about/support">
                            <span>Support</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                    <li>
                        <a {% if subpage == 'goodies' %} class="selected loaded"{% endif %} href="/about/goodies/">
                            <span>Goodies</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>

                    <li>
                        <a {% if subpage == 'careers' %} class="selected loaded"{% endif %} href="/about/careers/">
                            <span>Careers</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                    <li>
                        <a {% if subpage == 'press' %} class="selected loaded"{% endif %} href="/about/press/">
                            <span>Press</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                    <li>
                        <a {% if subpage == 'team' %} class="selected loaded"{% endif %} href="/about/team/">
                            <span>Team</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                </ul>
                <img id="NavRule" alt="Navigation Rule" src="/site_media/images/NavRule.png">
                <ul>
	                <li>
                        <a {% if subpage == 'terms' %} class="selected loaded"{% endif %} href="/about/terms/">
                            <span>Terms &amp; Privacy</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
	                <li>
                        <a {% if subpage == 'copyright' %} class="selected loaded"{% endif %} href="/about/copyright/">
                            <span>Copyright &amp; Trademark</span>
                            <span class="pointer normal"></span>
                            <span class="pointer hover"></span>
                        </a>
                    </li>
                </ul>
            </div><!-- #AboutLeft -->

            <div id="AboutRight">
            	{% if not subpage %}           
                    {% include "whatissocialmenu.html" %}
                {% elif subpage == 'etiquette' %}
                   {% include "etiquette.html" %}
                {% elif subpage == 'help' %}
                    {% include "help.html" %}
                {% elif subpage == 'support' %}
                    {% include "support.html" %}
                {% elif subpage == 'goodies' %}
                    {% include "goodies.html" %}
                {% elif subpage == 'careers' %}
                    {% include "careers.html" %}
                {% elif subpage == 'team' %}
                    {% include "team.html" %}
                {% elif subpage == 'terms' %}
                    {% include "terms.html" %}
                {% elif subpage == 'press' %}
                    {% include "press.html" %}
                {% elif subpage == 'copyright' %}
                    {% include "copyright.html" %}
                {% endif %}
            </div><!-- #AboutRight -->

        </div><!-- #AboutContent -->
    </div>
{% endblock %}

socialmenu/templates/changepassword.html
{% extends "profile_base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Menus for {{ username }}{% endblock %}
{% block external %}
<script type="text/javascript" src="/site_media/editprofile.js"></script>
{% endblock %}
{% block content %}
    {% include "user_header.html" %}
    <div class="FixedContainer">
        <form accept-charset="utf-8" method="POST" action="" class="Form StaticForm" id="profileEdit">
          {% csrf_token %}
          <h3>Change Password</h3>
            <ul>
                <li>
                    <label for="id_old_password">Old</label>
                    <div class="Right">
                    	{{form.old_password.errors}}
                        {{form.old_password}}
                        <span class="help_text">Your current password ·<a tabindex="-1" href="/password/reset/">Reset Password</a></span>
                        <span class="help_text"></span>
                    </div>
                </li>

                <li>
                    <label for="id_new_password1">New</label>
                    <div class="Right">
                        {{form.new_password1.errors}}
                        {{form.new_password1}}
                        <span class="help_text">Be tricky!</span>
                        <span class="help_text"></span>
                    </div>
                </li>

                <li>
                    <label for="id_new_password2">New, Again</label>
                    <div class="Right">
                        
                        {{form.new_password2.errors}}
                        {{form.new_password2}}
                        <span class="help_text">Confirm password</span>
                    </div>
                </li>

            </ul>

            <div class="Submit">
                <button type="submit" class="Button RedButton Button24">
                    Change Password
                </button>
            </div>
        </form>
    </div>
{% endblock %}

socialmenu/templates/context_bar.html
<script type="text/javascript" src="/site_media/follow_unfollow.js"></script>
{% load friendshiptags %}
{% followingcount actualuser as followingnum%}
{% followerscount actualuser as followernum%}

<div class="container sticky" id="ContextBar">
    <div class="FixedContainer">
        <ul class="links"> 
          <li>
          	  {% if not subpage %}
                  <a class="selected" href="/huangxia/">
              {% else %}
                  <a href="/user/{{username}}/">
              {% endif %}
              <strong>{{catagoryandmenu|length}}</strong> Catagories
              </a>
          </li>    
          <li>
          	{% if subpage and subpage == "menus" %}
                <a class="selected" href="/user/{{username}}/menus/">
            {% else %}
                <a href="/user/{{username}}/menus/">
            {% endif %}
            <strong>{{menus|length}}</strong> Menus
            </a>
          </li>    
          <li>
              <a href="/user/{{username}}/likes/">
                  <strong>{{likes}}</strong> Likes
              </a>
          </li>    
          <li>
              <a href="/huangxia/activity/">Activity</a>
          </li>

      </ul>
      <ul class="follow">    
          <li>
          	  {% if subpage and subpage == "followers" %}
                  <a class="selected" href="/user/{{username}}/followers/">
              {% else %}
                  <a  href="/user/{{username}}/followers/">
              {% endif %}
                  <strong>{{ followernum }}</strong> Followers
              </a>
          </li>
          
          <li>
          	  {% if subpage and subpage == "following" %}
                 <a class="selected" href="/user/{{username}}/following/">
              {% else %}
                 <a href="/user/{{username}}/following/">
              {% endif %}
                  <strong>{{followingnum}}</strong> Following
              </a>
          </li>            
      </ul>

      <div class="action">
      	  {% if userself %}
              <a href="/edit_profile/{{username}}/" class="Button13 Button WhiteButton Left Tab"><strong>Edit Profile</strong><span></span></a>
              <a tooltip="&lt;strong&gt;Rearrange Boards&lt;/strong&gt;" href="/sort_boards/" class="Button13 Button WhiteButton Right Tab" id="RearrangeButton"><strong></strong><span></span></a>
              <a href="#" tooltip="&lt;strong&gt;Cancel&lt;/strong&gt;" class="close hidden" id="RearrangeCancel">close</a>      
          {% else %}
              {% if isFriend %}
                  <a class="Button Button13 RedButton followuserbutton" action="{{username}}" data-text-unfollow="Unfollow All" data-text-follow="Follow All">Unfollow All </a>
              {% else %}
                  <a class="Button Button13 RedButton followuserbutton" action="{{username}}" data-text-unfollow="follow All" data-text-follow="Follow All"> Follow All </a>
              {% endif %}
          {% endif %}
          
      </div>      
  </div>
</div>

socialmenu/templates/copyright.html
<h1>Copyright and Trademark</h1>
<h2>Creating!!</h2>

socialmenu/templates/following.html
<script type="text/javascript" src="/site_media/profile_follow_unfollow.js"></script>
{% load friendshiptags %}
{% load getrange %}
{% load thumbnail %}
<div class="FixedContainer">
	<div id="PeopleList">
	    {% for following,menus in followingmenus.items %}
	        {% followingcount following as followingnum%}
            {% followerscount following as followernum%}
	        <div class="{% if forloop.counter|divisibleby:2 %}person{% else %}person odd{% endif %}">
                    {% thumbnail following.get_profile.avatar "180x240" crop="center" as im %}
	            <a style="background-image: url({{im.url}})" class="PersonImage ImgLink" href="/user/{{following.username}}/"></a>
                    {% endthumbnail %}
                <div class="PersonFollow">
                	{% if following in requestuser_all_followings %}
                        <a action="{{following.username}}" data-text-unfollow="Unfollow" data-text-follow="Follow" class="Button Button13 WhiteButton disabled clickable unfollowuserbutton">
                            Unfollow
                        </a>
                    {% else %}
                        <a action="{{following.username}}" data-text-unfollow="Unfollow" data-text-follow="Follow" class="Button Button13 WhiteButton clickable followuserbutton">
                            Follow
                        </a>
                    {% endif %}
	            </div>
	            <div class="PersonInfo">
                    <h4><a href="/user/{{following.username}}/">{{following.get_profile.firstname}} {{following.get_profile.lastname}}</a></h4>
                    <div class="stats">
                        <a href="/user/{{following.username}}/followers">
                            {{followernum}} Followers
                        </a> ·
                        <a href="/user/{{following.username}}/following">
                            {{followingnum}} Following
                        </a>
                    </div>
                    <div class="icons">
                    </div>
                </div>
            
            <div class="PersonPins">
            	{% for menu in menus %}
                    {% thumbnail menu.menuPics "75x75" crop="center" as im %}
            	    <a class="ImgLink" href="/menu/{{menu.id}}/"><img alt="{{menu.id}}" src="{{im.url}}"></a>
                    {% endthumbnail %}
            	{% endfor %}
            	{% for i in menus|length|getrange %}
            	    <span class="empty"></span>  
            	{% endfor %}
                
            </div>
        </div>
    	{% endfor %}
    </div>

socialmenu/templates/goodies.html
<h1>Goodies</h1>

    <h2>Please email us  -- info@bellasmenu.com.</h2>
    <p>Currently our iOS and Android Application are being development.We will let you knw once they are available.</p>

socialmenu/templates/menuSubmit_page.html
{% extends "base.html" %}
{% block title %}Submit Menu{% endblock %}

{% block head %}Submit Menu{% endblock %}
{% block content %}
    <h1 id="login_logo"><a href="/"></a></h1>
        <img class="login_bar" alt="Horizontal Rule" src="https://a248.e.akamai.net/passets.pinterest.com.s3.amazonaws.com/images/login_bar.png">
    <form id='menuSubmitForm' class='Form FancyForm1 AuthForm' method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save" />
    </form>
{% endblock %}

socialmenu/templates/popular.html
{% extends "base.html" %}
    {% block title %}Welcome to Social Menus{% endblock %}
    {% block head %}Welcome to Social Menus{% endblock %}
    {% block content %} 
        {% include "main_header.html" %}
        {% include "catagorybar.html" %}
        {% if not username %}
            {% include "unauthcallout.html" %}
        {% endif %}
        {% include "wrapper.html" %}
        {% include "search_autocomplete.html" %}
    {% endblock %}

socialmenu/templates/press.html
<h1>Press</h1>
<h2>Nothing Yet, but lets see!!</h2>

socialmenu/templates/wrapper.html
{% load modeandmultiply %}
{% load divide %}
{% load comments %}
{% load thumbnail %}
<script type="text/javascript" src="/site_media/jquery.js"></script>
<script type="text/javascript" src="/site_media/jquery.masonry.min.js"></script>
<script type="text/javascript" src="/site_media/search.js"></script>
<link rel="stylesheet" href="/site_media/jquery.autocomplete.css" type="text/css" />
<script type="text/javascript" src="/site_media/jquery.bgiframe.min.js"> </script>
<script type="text/javascript" src="/site_media/jquery.autocomplete.js"> </script>
<script type="text/javascript" src="/site_media/tag_autocomplete.js"> </script>
<script type="text/javascript" src="/site_media/wrapper.js"></script>
<script src="/site_media/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/site_media/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>


<div id="wrapper" class="BoardLayout" style="width: 1422px; opacity: 1; visibility: visible;">
	<div id="ColumnContainer">
		{% load endless %}
		{% lazy_paginate menus %}
		{%if menus%}
                    {% for menu in menus %}
		        <div class="pin" >
		        	
			        <div class="PinHolder">
				        <div class="actions">

                            <a href="/menu/takeit/" data-id="{{menu.id}}" class="Button Button11 WhiteButton ContrastButton repin_link">
                            <em></em>Takeit
                            </a>
                            {% if menu in likedMenus %}
                                <a href="#" data-text-unlike="Unlike" data-text-like="Like" data-id="{{menu.id}}" class="Button WhiteButton ContrastButton Button11 likebutton">
                                Unlike
                                </a>
                            {% else %}
                                <a href="#" data-text-unlike="Unlike" data-text-like="Like" data-id="{{menu.id}}" class="Button WhiteButton ContrastButton Button11 likebutton">
                                <em></em>Like
                                </a>
                            {% endif %}
                            <a  id="commentpin" thref="#" data-id="{{menu.id}}" class="Button Button11 WhiteButton ContrastButton comment">
                            <em></em>Comment
                            </a>
        
				        </div>
		        <a class="PinImage ImgLink" data-menu-id={{menu.id}}  href="{{menu.menuPics}}">{% thumbnail menu.menuPics "230x190" crop="center" as im %}<img class="PinImageImg" height="{{im.y}}" width="{{im.x}}" alt="{{im.url}}" src="{{im.url}}">{% endthumbnail %}</a>
			        </div>
			         <p class="description">
					        {{ menu.menuDescription}}
				     </p>
				     <p class="stats colorless">
                                         {% with menu.likedmenu_set.all|first as likedm %}
				     	     {% if likedm %}
				     	         {% if likedm.likes == 1 %}
				     	             <span class="LikesCount">1 like</span>
				     	         {% else %}
				     	             <span class="LikesCount">{{likedm.likes}} likes</span>
				     	         {% endif %}
                             {% else %}
                                 <span class="LikesCount">0 like</span>
                             {% endif %}
                         {% endwith %}  
                         <span class="CommentsCount hidden"></span>
                         <span class="RepinsCount">1 takeit</span>    
                     </p>
                     <div class="comments colormuted">
                     	 {% get_comment_list for menus.menu menu.id as comment_list %}
                     	 {% get_comment_count for menus.menu menu.id as comment_count%}
                     	 {% if comment_count <= 5 %}   
                     	     {% for comment in comment_list %}       
                                 <div comment-id="{{comment.id}}" class="comment convo clearfix"> 
                                     <a class="ImgLink" href="/user/{{comment.username}}/">
                                         {% thumbnail comment.user.get_profile.avatar "50x50" crop="center" as im %}
                                         <img alt="Profile picture of {{comment.username}}" class="profile user_image" src="{{im.url}}">
                                         {% endthumbnail %}
                                     </a>
                                     <p><a href="/user/{{ comment.user_name }}/">{{ comment.user_name }}</a> {{ comment.comment }}</p>
                                 </div>
                             {% endfor %}
                         {% else %}
                             {% for comment in comment_list|slice:":5" %}       
                                 <div comment-id="{{comment.id}}" class="comment convo clearfix"> 
                                     <a class="ImgLink" href="user/{{comment.username}}/">
                                         <img alt="Profile picture of {{comment.username}}" class="profile user_image" src="{{comment.user.get_profile.avatar}}">
                                     </a>
                                     <p><a href="/user/{{ comment.user_name }}/">{{ comment.user_name }}</a> {{ comment.comment }}</p>
                                 </div>
                             {% endfor %}
                             <a class="all comment convo clearfix" href="/menu/{{menu.id}}/">All {{comment_count}} Comments…</a>
                         {% endif %}   
                      </div>
                      <div id="commentarea" class="write convo clearfix" style="display:none;">
                          <a class="ImgLink" href="/user/{{actualuser.username}}/">
                          {% thumbnail actualuser.get_profile.avatar "50x50" crop="center" as im %}
                              <img alt="Profile picture of you" src="{{im.url}}">
                           {% endthumbnail %}
                          </a>
                          {% get_comment_form for menu as form%}
                          <form method="POST" action="{% comment_form_target %}">
                          	{% csrf_token %}
                          	  {% for field in form %}
                                  {% if field.is_hidden %}
                                      {{ field }}
                                  {% else %}
                                      {% if field.name != "name" and field.name != "email" and field.name != "url" and field.name != "comment" and field.name != "honeypot" %}
                                          {% if field.errors %}{{ field.errors }}{% endif %}
                                              {{ field }}
                                          {% endif %}
                                  {% endif %}
                              {% endfor %}
                              <input type="hidden" class="pin_comment_replies" name="replies">
                              <input type="hidden" class="usercommented" value="{{username}}">
                              <textarea placeholder="Add a comment..." maxlength="1000" class="GridComment" name="comment"></textarea>
                              <button id="commentbutton" type="submit" class="Button WhiteButton Button11 grid_comment_button">Comment</button>
                          </form>
                      </div>
		          </div>
		     {% endfor %}
		     {% show_more %}
		{% else %}
		    <h1>No menus for you</h1>
		{% endif %}
		<button id="ScrollToTop" class="Button WhiteButton Indicator Offscreen" type="button"> Scroll to Top </button>
	</div>
</div>